apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  namespace: default
  name: myclaim
spec:
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
#  storageClassName: standard
