apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: XXX
#  namespace: default
subjects:
- kind: User
  name: username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: name_of_role
  apiGroup: rbac.authorization.k8s.io
