apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
#  namespace: default
  name: XXX
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # same as ["*"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
