apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: XXX
  labels:
    k: v
spec:
  selector:
    k: v  # Must match at least one pod label pair
# OR ClusterIp
  type: ClusterIP
  ports:
  - port: 80 # service port
    targetPort: 4000  # container port
    protocol: TCP
# OR NodePort
#  type: NodePort
#  ports:
#  - port: 80 # service port
#    targetPort: 4000  # container port
#    nodePort: 30000  # cluster port (for external access)
#    protocol: TCP
